### ISSUE TITLE
Bluetooth Pairing Problem

### ISSUE THREAD

**Issue by Sumitlad** [Cloudslab/FogBus#1]
Hello, I am using BPL iOxy Pulse Meter Device, When i try to connect device with app... pairing wont happen... When i try to enter name of pairing device.. error occurs and Stops App. Please provide solution or any suggestions...

**Comment by shreshthtuli** [comment]
Hi Sumitlad, please use the latest version of the HealthKeeper app. Download from https://github.com/Cloudslab/FogBus/raw/master/Android-app/New-BLE/MIT-AppInventor/HealthKeeper_v3.apk

If it still doesn't work, please let me know the device ID of the oximeter you are using
