### ISSUE TITLE
Package 'mysql-server' has no installation candidate

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus#2]
pi@raspberrypi:~ $ sudo apt-get install mysql-server -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.0

E: Package 'mysql-server' has no installation candidate

Please solve the issue.

**Comment by shreshthtuli** [comment]
Use this: sudo apt install mariadb-server

**Comment by AbhilashPati** [comment]
Thanks a lot...
