### ISSUE TITLE
Issue relating Installing FogBus

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus#3]
pi@raspberrypi:~ $ dos2unix ./FogBus/Install-scripts/* && sudo chmod +x ./FogBus/Install-scripts/*
dos2unix: Failed to open temporary output file: Permission denied
dos2unix: problems converting file ./FogBus/Install-scripts/fogbus-install-master.sh
dos2unix: Failed to open temporary output file: Permission denied
dos2unix: problems converting file ./FogBus/Install-scripts/fogbus-install-worker.sh

Please solve the issue

**Comment by shreshthtuli** [comment]
Use sudo

**Comment by AbhilashPati** [comment]
Thanks a lot...
