### ISSUE TITLE
Facing problem when downloading data from the link given in manuals for Healthkeeper to be transfered  in the Worker node

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus#4]
Facing problem when downloading data from the link given in manuals.

https://drive.google.com/open?id=1DZWaJHHNMrJFnsCfxoWSIpfDhK7n-qHH

ERROR 404: Page not found

**Comment by shreshthtuli** [comment]
Transfer files in this folder instead: https://github.com/Cloudslab/FogBus/tree/master/Browser-src/RPi/Worker

**Comment by AbhilashPati** [comment]
Thanks a lot...
