### ISSUE TITLE
Issue regarding the installation of oracle-java8-jdk 

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus#5]
pi@raspberrypi:~ $ sudo apt-get install oracle-java8-jdk -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package oracle-java8-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-jdk' has no installation candidate

Please solve the issue

**Comment by shreshthtuli** [comment]
Use this: sudo apt install default-jdk -y

**Comment by AbhilashPati** [comment]
Thanks a lot...
