### ISSUE TITLE
Unable to compile Analyzer.java

### ISSUE THREAD

**Issue by AbhilashPati** [Cloudslab/FogBus#6]
pi@raspberrypi:/var/www/html/HealthKeeper $ javac /var/www/html/HealthKeeper/WorkerInterface/Analyzer_files/Analyzer.java
/var/www/html/HealthKeeper/WorkerInterface/Analyzer_files/Analyzer.java:29: error: cannot find symbol
		AnalyzerO2 a1 = new AnalyzerO2();
		^
  symbol:   class AnalyzerO2
  location: class Analyzer
/var/www/html/HealthKeeper/WorkerInterface/Analyzer_files/Analyzer.java:29: error: cannot find symbol
		AnalyzerO2 a1 = new AnalyzerO2();
		                    ^
  symbol:   class AnalyzerO2
  location: class Analyzer
/var/www/html/HealthKeeper/WorkerInterface/Analyzer_files/Analyzer.java:30: error: cannot find symbol
		AnalyzerBPM a2 = new AnalyzerBPM();
		^
  symbol:   class AnalyzerBPM
  location: class Analyzer
/var/www/html/HealthKeeper/WorkerInterface/Analyzer_files/Analyzer.java:30: error: cannot find symbol
		AnalyzerBPM a2 = new AnalyzerBPM();
		                     ^
  symbol:   class AnalyzerBPM
  location: class Analyzer
4 errors
pi@raspberrypi:/var/www/html/HealthKeeper $ 

Please solve the issue

**Comment by shreshthtuli** [comment]
Use existing jar file
